#!/bin/sh

# R -> Templater
# T -> Template
# B -> Builder

for r in 1 2 3 4 5; do
for t in 1 2 3 4 5; do

##################################################

R_COUNT=$r
T_COUNT=$t

R_NAME="Templater${R_COUNT}x${T_COUNT}"
B_NAME="Templater${R_COUNT}x${T_COUNT}Builder"
T_NAME="Template${T_COUNT}"

R_FILE="${R_NAME}.java"
B_FILE="${B_NAME}.java"

RG=$(sed 's/.\{1\}$//' <<< $(seq -f "T%g" -s ", " 1 $R_COUNT))
TG=$(sed 's/.\{1\}$//' <<< $(seq -f "U%g" -s ", " 1 $T_COUNT))

RD=$(sed 's/.\{1\}$//' <<< $(replace '0' ' arg' <<< $(seq -f "T%g" -s ", " 101 101 "${R_COUNT}0${R_COUNT}")))
TD=$(sed 's/.\{1\}$//' <<< $(replace '0' ' arg' <<< $(seq -f "U%g" -s ", " 101 101 "${T_COUNT}0${T_COUNT}")))

RA=$(sed 's/.\{1\}$//' <<< $(seq -f "arg%g" -s ", " 1 $R_COUNT))
TA=$(sed 's/.\{1\}$//' <<< $(seq -f "arg%g" -s ", " 1 $T_COUNT))

echo "$R_FILE..."
rm -f $R_FILE
echo "/* WARNING! This file is autogenerated by a script. */"     >> $R_FILE
echo "package org.bakasoft.framboyan.templaters;"                 >> $R_FILE
echo ""                                                           >> $R_FILE
echo "import java.util.ArrayList;"                                >> $R_FILE
echo ""                                                           >> $R_FILE
echo "import org.bakasoft.framboyan.templates.${T_NAME};"         >> $R_FILE
echo ""                                                           >> $R_FILE
echo "public class ${R_NAME}<${RG}, ${TG}> {"                     >> $R_FILE
echo ""                                                           >> $R_FILE
echo "	private final ${B_NAME}<${RG}, ${TG}> builder;"           >> $R_FILE
echo ""                                                           >> $R_FILE
echo "	public ${R_NAME}(${B_NAME}<${RG}, ${TG}> builder) {"      >> $R_FILE
echo "		this.builder = builder;"                              >> $R_FILE
echo "	}"                                                        >> $R_FILE
echo ""                                                           >> $R_FILE
echo "	public Batch using(${RD}) {"                              >> $R_FILE
echo "		return new Batch().using(${RA});"                     >> $R_FILE
echo "	}"                                                        >> $R_FILE
echo ""                                                           >> $R_FILE
echo "	public class Batch {"                                     >> $R_FILE
echo ""                                                           >> $R_FILE
echo "		private final ArrayList<${T_NAME}<${TG}>> templates;" >> $R_FILE
echo ""                                                           >> $R_FILE
echo "		public Batch() {"                                     >> $R_FILE
echo "			this.templates = new ArrayList<>();"              >> $R_FILE
echo "		}"                                                    >> $R_FILE
echo ""                                                           >> $R_FILE
echo "		public Batch using(${RD}) {"                          >> $R_FILE
echo "			templates.add(builder.build(${RA}));"             >> $R_FILE
echo "			return this;"                                     >> $R_FILE
echo "		}"                                                    >> $R_FILE
echo ""                                                           >> $R_FILE
echo "		public Batch test(${TD}) {"                           >> $R_FILE
echo "			if (templates.isEmpty()) {"                       >> $R_FILE
echo "				throw new RuntimeException();"                >> $R_FILE
echo "			}"                                                >> $R_FILE
echo ""                                                           >> $R_FILE
echo "			for (${T_NAME}<${TG}> template : templates) {"    >> $R_FILE
echo "				template.test(${TA});"                        >> $R_FILE
echo "			}"                                                >> $R_FILE
echo ""                                                           >> $R_FILE
echo "			return this;"                                     >> $R_FILE
echo "		}"                                                    >> $R_FILE
echo "	}"                                                        >> $R_FILE
echo "}"                                                          >> $R_FILE

echo "$B_FILE..."
rm -f $B_FILE
echo "/* WARNING! This file is autogenerated by a script. */"     >> $B_FILE
echo "package org.bakasoft.framboyan.templaters;"                 >> $B_FILE
echo ""                                                           >> $B_FILE
echo "import org.bakasoft.framboyan.templates.${T_NAME};"         >> $B_FILE
echo ""                                                           >> $B_FILE
echo "@FunctionalInterface"                                       >> $B_FILE
echo "public interface ${B_NAME}<${RG}, ${TG}> {"                 >> $B_FILE
echo ""                                                           >> $B_FILE
echo "	${T_NAME}<${TG}> build(${RD});"                           >> $B_FILE
echo ""                                                           >> $B_FILE
echo "}"                                                          >> $B_FILE
##################################################

done
done