/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import java.util.ArrayList;

import org.bakasoft.framboyan.exceptions.MissingTestException;
import org.bakasoft.framboyan.templates.Template4;

public class Templater1x4<T1, U1, U2, U3, U4> {

	private final Templater1x4Builder<T1, U1, U2, U3, U4> builder;

	public Templater1x4(Templater1x4Builder<T1, U1, U2, U3, U4> builder) {
		this.builder = builder;
	}

	public Batch using(T1 arg1) {
		return new Batch().using(arg1);
	}

	public class Batch {

		private final ArrayList<Template4<U1, U2, U3, U4>> templates;

		public Batch() {
			this.templates = new ArrayList<>();
		}

		public Batch using(T1 arg1) {
			templates.add(builder.build(arg1));
			return this;
		}

		public Batch test(U1 arg1, U2 arg2, U3 arg3, U4 arg4) {
			if (templates.isEmpty()) {
				throw new MissingTestException();
			}

			for (Template4<U1, U2, U3, U4> template : templates) {
				template.test(arg1, arg2, arg3, arg4);
			}

			return this;
		}
	}
}
