/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

public interface Templaters {

    default <T1, U1> Templater1x1<T1, U1> templater(Templater1x1Builder<T1, U1> builder) {
        return new Templater1x1<>(builder);
    }

    default <T1, U1, U2> Templater1x2<T1, U1, U2> templater(Templater1x2Builder<T1, U1, U2> builder) {
        return new Templater1x2<>(builder);
    }

    default <T1, U1, U2, U3> Templater1x3<T1, U1, U2, U3> templater(Templater1x3Builder<T1, U1, U2, U3> builder) {
        return new Templater1x3<>(builder);
    }

    default <T1, U1, U2, U3, U4> Templater1x4<T1, U1, U2, U3, U4> templater(Templater1x4Builder<T1, U1, U2, U3, U4> builder) {
        return new Templater1x4<>(builder);
    }

    default <T1, U1, U2, U3, U4, U5> Templater1x5<T1, U1, U2, U3, U4, U5> templater(Templater1x5Builder<T1, U1, U2, U3, U4, U5> builder) {
        return new Templater1x5<>(builder);
    }

    default <T1, T2, U1> Templater2x1<T1, T2, U1> templater(Templater2x1Builder<T1, T2, U1> builder) {
        return new Templater2x1<>(builder);
    }

    default <T1, T2, U1, U2> Templater2x2<T1, T2, U1, U2> templater(Templater2x2Builder<T1, T2, U1, U2> builder) {
        return new Templater2x2<>(builder);
    }

    default <T1, T2, U1, U2, U3> Templater2x3<T1, T2, U1, U2, U3> templater(Templater2x3Builder<T1, T2, U1, U2, U3> builder) {
        return new Templater2x3<>(builder);
    }

    default <T1, T2, U1, U2, U3, U4> Templater2x4<T1, T2, U1, U2, U3, U4> templater(Templater2x4Builder<T1, T2, U1, U2, U3, U4> builder) {
        return new Templater2x4<>(builder);
    }

    default <T1, T2, U1, U2, U3, U4, U5> Templater2x5<T1, T2, U1, U2, U3, U4, U5> templater(Templater2x5Builder<T1, T2, U1, U2, U3, U4, U5> builder) {
        return new Templater2x5<>(builder);
    }

    default <T1, T2, T3, U1> Templater3x1<T1, T2, T3, U1> templater(Templater3x1Builder<T1, T2, T3, U1> builder) {
        return new Templater3x1<>(builder);
    }

    default <T1, T2, T3, U1, U2> Templater3x2<T1, T2, T3, U1, U2> templater(Templater3x2Builder<T1, T2, T3, U1, U2> builder) {
        return new Templater3x2<>(builder);
    }

    default <T1, T2, T3, U1, U2, U3> Templater3x3<T1, T2, T3, U1, U2, U3> templater(Templater3x3Builder<T1, T2, T3, U1, U2, U3> builder) {
        return new Templater3x3<>(builder);
    }

    default <T1, T2, T3, U1, U2, U3, U4> Templater3x4<T1, T2, T3, U1, U2, U3, U4> templater(Templater3x4Builder<T1, T2, T3, U1, U2, U3, U4> builder) {
        return new Templater3x4<>(builder);
    }

    default <T1, T2, T3, U1, U2, U3, U4, U5> Templater3x5<T1, T2, T3, U1, U2, U3, U4, U5> templater(Templater3x5Builder<T1, T2, T3, U1, U2, U3, U4, U5> builder) {
        return new Templater3x5<>(builder);
    }

    default <T1, T2, T3, T4, U1> Templater4x1<T1, T2, T3, T4, U1> templater(Templater4x1Builder<T1, T2, T3, T4, U1> builder) {
        return new Templater4x1<>(builder);
    }

    default <T1, T2, T3, T4, U1, U2> Templater4x2<T1, T2, T3, T4, U1, U2> templater(Templater4x2Builder<T1, T2, T3, T4, U1, U2> builder) {
        return new Templater4x2<>(builder);
    }

    default <T1, T2, T3, T4, U1, U2, U3> Templater4x3<T1, T2, T3, T4, U1, U2, U3> templater(Templater4x3Builder<T1, T2, T3, T4, U1, U2, U3> builder) {
        return new Templater4x3<>(builder);
    }

    default <T1, T2, T3, T4, U1, U2, U3, U4> Templater4x4<T1, T2, T3, T4, U1, U2, U3, U4> templater(Templater4x4Builder<T1, T2, T3, T4, U1, U2, U3, U4> builder) {
        return new Templater4x4<>(builder);
    }

    default <T1, T2, T3, T4, U1, U2, U3, U4, U5> Templater4x5<T1, T2, T3, T4, U1, U2, U3, U4, U5> templater(Templater4x5Builder<T1, T2, T3, T4, U1, U2, U3, U4, U5> builder) {
        return new Templater4x5<>(builder);
    }

    default <T1, T2, T3, T4, T5, U1> Templater5x1<T1, T2, T3, T4, T5, U1> templater(Templater5x1Builder<T1, T2, T3, T4, T5, U1> builder) {
        return new Templater5x1<>(builder);
    }

    default <T1, T2, T3, T4, T5, U1, U2> Templater5x2<T1, T2, T3, T4, T5, U1, U2> templater(Templater5x2Builder<T1, T2, T3, T4, T5, U1, U2> builder) {
        return new Templater5x2<>(builder);
    }

    default <T1, T2, T3, T4, T5, U1, U2, U3> Templater5x3<T1, T2, T3, T4, T5, U1, U2, U3> templater(Templater5x3Builder<T1, T2, T3, T4, T5, U1, U2, U3> builder) {
        return new Templater5x3<>(builder);
    }

    default <T1, T2, T3, T4, T5, U1, U2, U3, U4> Templater5x4<T1, T2, T3, T4, T5, U1, U2, U3, U4> templater(Templater5x4Builder<T1, T2, T3, T4, T5, U1, U2, U3, U4> builder) {
        return new Templater5x4<>(builder);
    }

    default <T1, T2, T3, T4, T5, U1, U2, U3, U4, U5> Templater5x5<T1, T2, T3, T4, T5, U1, U2, U3, U4, U5> templater(Templater5x5Builder<T1, T2, T3, T4, T5, U1, U2, U3, U4, U5> builder) {
        return new Templater5x5<>(builder);
    }

}
