/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import java.util.ArrayList;

import org.bakasoft.framboyan.templates.Template1;

public class Templater1x1<T1, U1> {

	private final Templater1x1Builder<T1, U1> builder;

	public Templater1x1(Templater1x1Builder<T1, U1> builder) {
		this.builder = builder;
	}

	public Batch using(T1 arg1) {
		return new Batch().using(arg1);
	}

	public class Batch {

		private final ArrayList<Template1<U1>> templates;

		public Batch() {
			this.templates = new ArrayList<>();
		}

		public Batch using(T1 arg1) {
			templates.add(builder.build(arg1));
			return this;
		}

		public Batch test(U1 arg1) {
			if (templates.isEmpty()) {
				throw new RuntimeException();
			}

			for (Template1<U1> template : templates) {
				template.test(arg1);
			}

			return this;
		}
	}
}
