/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import org.bakasoft.framboyan.templates.Template5;

@FunctionalInterface
public interface Templater1x5Builder<T1, U1, U2, U3, U4, U5> {

	Template5<U1, U2, U3, U4, U5> build(T1 arg1);

}
