/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import java.util.ArrayList;

import org.bakasoft.framboyan.exceptions.MissingTestException;
import org.bakasoft.framboyan.templates.Template2;

public class Templater1x2<T1, U1, U2> {

	private final Templater1x2Builder<T1, U1, U2> builder;

	public Templater1x2(Templater1x2Builder<T1, U1, U2> builder) {
		this.builder = builder;
	}

	public Batch using(T1 arg1) {
		return new Batch().using(arg1);
	}

	public class Batch {

		private final ArrayList<Template2<U1, U2>> templates;

		public Batch() {
			this.templates = new ArrayList<>();
		}

		public Batch using(T1 arg1) {
			templates.add(builder.build(arg1));
			return this;
		}

		public Batch test(U1 arg1, U2 arg2) {
			if (templates.isEmpty()) {
				throw new MissingTestException();
			}

			for (Template2<U1, U2> template : templates) {
				template.test(arg1, arg2);
			}

			return this;
		}
	}
}
