/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import org.bakasoft.framboyan.templates.Template1;

@FunctionalInterface
public interface Templater4x1Builder<T1, T2, T3, T4, U1> {

	Template1<U1> build(T1 arg1, T2 arg2, T3 arg3, T4 arg4);

}
