/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import org.bakasoft.framboyan.templates.Template4;

@FunctionalInterface
public interface Templater2x4Builder<T1, T2, U1, U2, U3, U4> {

	Template4<U1, U2, U3, U4> build(T1 arg1, T2 arg2);

}
