/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import org.bakasoft.framboyan.templates.Template3;

@FunctionalInterface
public interface Templater1x3Builder<T1, U1, U2, U3> {

	Template3<U1, U2, U3> build(T1 arg1);

}
