/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import org.bakasoft.framboyan.templates.Template5;

@FunctionalInterface
public interface Templater5x5Builder<T1, T2, T3, T4, T5, U1, U2, U3, U4, U5> {

	Template5<U1, U2, U3, U4, U5> build(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5);

}
