/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import org.bakasoft.framboyan.templates.Template3;

@FunctionalInterface
public interface Templater4x3Builder<T1, T2, T3, T4, U1, U2, U3> {

	Template3<U1, U2, U3> build(T1 arg1, T2 arg2, T3 arg3, T4 arg4);

}
