/* WARNING! This file is autogenerated by a script. */
package org.bakasoft.framboyan.templaters;

import org.bakasoft.framboyan.templates.Template2;

@FunctionalInterface
public interface Templater1x2Builder<T1, U1, U2> {

	Template2<U1, U2> build(T1 arg1);

}
